### ISSUE TITLE
Empty SQL strings

### ISSUE THREAD

**Issue by contang0** [pdet/duckdb-tutorial#4]
Hello,

I was trying to follow [the first](https://raw.githubusercontent.com/pdet/duckdb-tutorial/master/Part%201/Exercise/Exercise.ipynb) part of the tutorial, but I am getting an error which seems to be due the fact that the SQL strings `load_cab_trip_sql` and `load_weather_sql` are empty, or am I missing something?

Thanks!

![image](https://user-images.githubusercontent.com/10067941/137229803-84bc3012-cf7a-40bf-a554-0b1fb4bc0994.png)

**Comment by pdet** [comment]
Hi @juliuscrn these are intentional, we use this tutorial in conferences and in college lectures, so the idea is that the participants do this hands-on  there.

**Comment by contang0** [comment]
Understood, thank you!
