### ISSUE TITLE
Taxi data is now stored in parquet format instead of csv

### ISSUE THREAD

**Issue by stevenlw-porpoise** [pdet/duckdb-tutorial#5]
The link to the taxi dataset in part 1 (https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-01.csv) is broken and the [correct link](https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2016-01.parquet) has a .parquet extension. According to the [NYC TLC](https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page) this was changed May 13, 2022.

In order to fix it, not only does the link need to be changed but I don't see a parquet equivalent of `from_csv_auto` to load in to the relational API.

Alternatively, the CSV dataset might be available somewhere else. It is on [Kaggle](https://www.kaggle.com/datasets/elemento/nyc-yellow-taxi-trip-data?select=yellow_tripdata_2016-01.csv) although I don't think this is accessible without Kaggle username and password (I haven't tried though so I might be wrong - just looking at the [kaggle cli](https://github.com/floydwch/kaggle-cli) which requires it).

**Comment by pdet** [comment]
Hey Steven, I modified the exercise to use the parquet file since the csv was deprecated.

Thanks for opening up this issue!
